### PR TITLE
Fix Binder links

### PR DESCRIPTION
**Pull request by brian-rose**
Addresses https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/issues/85 for this repo.

### CODE REVIEW

**Comment by mgrover1** [comment]
@brian-rose I think we can use https://aws-uswest2-binder.pangeo.io.. it just requires people have a github account

**Comment by brian-rose** [comment]
@mgrover1 no problem, if you want to try that for this Cookbook! At today's IWG we decided that it was top priority to get the broken links fixed, and mybinder.org was path of least resistance.

I'll update this PR to use https://aws-uswest2-binder.pangeo.io/ instead, it will be good to experiment with it.

**Comment by mgrover1** [comment]
Thanks @brian-rose !!

**Comment by mgrover1** [comment]
@brian-rose currently testing it to make sure the binder builds

**Review by mgrover1 — APPROVED** [review]
Thanks @brian-rose for taking care of this! Looks like it runs :)

**Pull request merged**
